apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - second-app
    #matchLabels:
      # app: second-app
      # tier: backend
  replicas: 3
  template:     
    metadata:
      labels: 
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: marclameu/kub-first-app:2
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
