
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
    tier: backend
  ports:
    - protocol: 'TCP'  
      port: 3001
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  selector:
    matchLabels:
      app: second-app
      tier: backend
  replicas: 3
  template:     
    metadata:
      labels: 
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: marclameu/kub-first-app:2
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
