pipeline {
    agent any

    stages {
        stage('Build Image') {
            steps {
                script {
                    def dockerApp = docker.build("marclameu/users-api", '-f Dockerfile .'){}
                }
            }
        }
    }
}