apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tasks
  template: 
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: marclameu/kub-demo-tasks:39
          env:
            - name: AUTH_ADRESS
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: "tasks"